# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: '3.5'

services:
  # App backend service
  app-server:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    restart: always
    depends_on:
      - db
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - localnetwork

  # Frontend Service
  app-client:
    build:
      context: ui
      dockerfile: Dockerfile
    ports:
      - "9090:80"
    restart: always
    depends_on:
      - app-server
    networks:
      - localnetwork
    
  db:
    image: postgres:12.1-alpine
    container_name: app_db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      #- ./database/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - database-data:/var/lib/postgresql/data/
    networks:
      - localnetwork  

volumes:
  database-data:
  
# Networks to be created to facilitate communication between containers
networks:
  localnetwork:
    driver: bridge
