server:
  port: 8082

spring:
  datasource:
    driverClassName:  org.postgresql.Driver
    url: jdbc:postgresql://db:5432/rates_db
    username: app_user
    password: 58gh95
    hikari:
      maximumIdle: 2
      maximum-pool-size: 8
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        ddl-auto: validate
        hbm2ddl.auto: validate
        show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect